name: Deploy Frontend to Mika Server

on:
    push:
        branches:
            - master

jobs:
    deploy:
        runs-on: self-hosted

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "18"

            - name: Install dependencies
              run: npm install

            - name: Build project
              run: npm run build

            - name: Run deploy script on server
              run: bash /home/s_winklerf23/apps/mika-frontend/scripts/mika-deploy.sh
