name: Deploy Frontend to Mika Server

on:
    push:
        branches:
            - master

jobs:
    deploy:
        runs-on: self-hosted

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "18"

            - name: Enable Corepack (Yarn)
              run: corepack enable

            - name: Install dependencies
              run: yarn install --frozen-lockfile

            - name: Build project
              run: yarn build

            - name: Run deploy script
              run: bash ./scripts/mika-deploy.sh
